apiVersion: v1
kind: Secret
metadata:
  name: ai-gateway-secrets
  namespace: ai-gateway-mesh
type: Opaque
stringData:
  small-model-api-key: demo
  large-model-api-key: demo
  coder-model-api-key: demo
