apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus.ai-gateway-mesh.svc.cluster.local:9090
    isDefault: true
    editable: true
